POST http://localhost:3000/user
content-type: application/json

{
    "firstName": "Marcos",
    "lastName": "Silva",
    "email": "marcos.henrique@toptal.com",
    "password": "s3cr3tp4sswo4rd"
}

###
GET http://localhost:3000/user/6239b5481018ca5c919e3b3d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM5YjU0ODEwMThjYTVjOTE5ZTNiM2QiLCJlbWFpbCI6Im1hcmNvcy5oZW5yaXF1ZUB0b3B0YWwuY29tIiwicGVybWlzc2lvbkxldmVsIjoxLCJwcm92aWRlciI6ImVtYWlsIiwibmFtZSI6Ik1hcmNvcyBTaWx2YSIsInJlZnJlc2hLZXkiOiJzbnYyRFJ2SG5wdkN0OUZsd0ZWNi93PT0iLCJpYXQiOjE2NDc5NTAxNjV9.TaYoV2pGRomYaS5GPUFUx4bRbdcMrbkfBRXYGORUQsI

###
GET http://localhost:3000/user/list

###
DELETE http://localhost:3000/user/62384541f3ff44f4947afede