POST http://localhost:3000/user
content-type: application/json

{
    "firstName": "Marcos",
    "lastName": "Silva",
    "email": "marcos.henrique@toptal.com",
    "password": "s3cr3tp4sswo4rd"
}

###
GET http://localhost:3000/user/62384424782c46d6c55c2dc1

###
GET http://localhost:3000/user/list

###
DELETE http://localhost:3000/user/62384541f3ff44f4947afede