@baseUrl = http://localhost:3000/user
###
POST {{baseUrl}}/user
content-type: application/json

{
    "firstName": "Marcos",
    "lastName": "Silva",
    "email": "marcos.henrique@toptal.com",
    "password": "s3cr3tp4sswo4rd"
}

###
GET {{baseUrl}}/62384424782c46d6c55c2dc1

###
GET {{baseUrl}}/list

###
DELETE {{baseUrl}}/62384541f3ff44f4947afede